### ISSUE TITLE
 When using REI to find the recipe for "diced_potato," the client crashes.

### ISSUE THREAD

**Issue by RookiesTwo** [axperty/moredelight-fabric#13]
FULL CRASH REPORT:
[crash-2024-07-18_16.06.47-client.txt](https://github.com/user-attachments/files/16279881/crash-2024-07-18_16.06.47-client.txt)

Game version: 1.20.1
Loader: Fabric
FabricAPI version: 0.92.2
REI version: 12.1.725-fabric
MOD version: 1.2.2-1.20.1-fabric

**Comment by axperty** [comment]
Hi RookiesTwo,

The issue you're experiencing is due to the older port, Farmer's Delight [Fabric], not being updated to work well with Roughly Enough Items. I recommend using the newer and updated port, [Farmer's Delight Refabricated](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated). More Delight has been updated to work with this port, as the older one has been marked as deprecated and will no longer receive updates.

If you have any more questions, feel free to ask.

Have a good day,
Axperty.

---
If you want to support the creation of Minecraft mods, consider making a donation through [PayPal.](https://paypal.me/kevgelhorn)
