### ISSUE TITLE
Compat Issue with a lot wooden blocks

### ISSUE THREAD

**Issue by suerion** [axperty/moredelight-fabric#2]
Hey, i had a huge modpack, in it there are a lot off wood Compat issues, i would add here the Log file  and the Compat issues exclusive 

hope i could help with this compat issue to fix it.

Complete Server log: https://mclo.gs/F2HIY7N

Compat Issues: https://mclo.gs/VmRyK7W

**Comment by axperty** [comment]
Hi suerion,

What I saw quickly, seems like loot_tables are causing some problems, I'll look into it as soon as possible, thank you for letting me know.

**Comment by axperty** [comment]
Hi suerion,

After taking a look, I recommend you to [update More Delight](https://www.curseforge.com/minecraft/mc-mods/more-delight-fabric/files/all?page=1&pageSize=20) to its latest version and [download Storage Delight.](https://www.curseforge.com/minecraft/mc-mods/storage-delight-fabric/files/all?page=1&pageSize=20)
**Why:** I had to move the drawers and glass cabinets to other mod mod because I was also getting a lot of compatibility issues, the way they were coded wasn't the best. 
Now they work exactly like cabinets from Farmer's Delight, so there shouldn't be any issues.

Make a copy of your world before doing this, if you have drawers or glass cabinets placed **they will be erased** as More Delight **doesn't have them** anymore.

Have a good day.

**Comment by suerion** [comment]
> Hi suerion,
> 
> After taking a look, I recommend you to [update More Delight](https://www.curseforge.com/minecraft/mc-mods/more-delight-fabric/files/all?page=1&pageSize=20) to its latest version and [download Storage Delight.](https://www.curseforge.com/minecraft/mc-mods/storage-delight-fabric/files/all?page=1&pageSize=20) **Why:** I had to move the drawers and glass cabinets to other mod mod because I was also getting a lot of compatibility issues, the way they were coded wasn't the best. Now they work exactly like cabinets from Farmer's Delight, so there shouldn't be any issues.
> 
> Make a copy of your world before doing this, if you have drawers or glass cabinets placed **they will be erased** as More Delight **doesn't have them** anymore.
> 
> Have a good day.

Hey thanks a lot :) worked fine for me, 

i'm looking forward :)

**Comment by axperty** [comment]
Thank you for your support and using my mods :)
